version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data